# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('coin', models.CharField(default='UNKNOWN', max_length=12)),
                ('market_cap', models.PositiveIntegerField(null=True)),
                ('price_btc', models.DecimalField(decimal_places=11, max_digits=11, null=True)),
                ('price_usd', models.DecimalField(decimal_places=11, max_digits=11, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
