# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptohistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='timestamp',
            new_name='dt',
        ),
    ]
