# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptohistory', '0002_auto_20180118_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='price_btc',
            field=models.DecimalField(decimal_places=11, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price_usd',
            field=models.DecimalField(decimal_places=11, max_digits=22, null=True),
        ),
    ]
