# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptohistory', '0003_auto_20180118_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('dt', 'coin')]),
        ),
    ]
