# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptohistory', '0004_auto_20180118_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
