# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20180117_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='ts_raw',
        ),
    ]
